version: '2'
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname:  rabbitmq
    restart: always
    #此环境变量设置rabbitmq 的初始 用户，密码，和vhost，并且删除了默认的guest用户
    #此变量与spring－service中的变量设置一致，一同修改
    environment:
      RABBITMQ_DEFAULT_USER: wfij
      RABBITMQ_DEFAULT_PASS: kkslcm8923s
      RABBITMQ_DEFAULT_VHOST: /wfij
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - wfij

 

  spring-service:
    image: spring-service:0.0.1-SNAPSHOT
    container_name: springservice
    restart: always
# 通过环境变量，让useraccount访问mongo
    environment:
      RABBIT_HOST: rabbitmq
    ports:
      - "8080:8080"
    networks:
      - wfij
    depends_on:
      - rabbitmq



networks:
  wfij:
    external:
      name: wfij-net





