spring:
  rabbitmq:
    
    host: ${rabbit.host:localhost}
    port: 5672
    username: wfij
    password:  kkslcm8923s
    virtual-host: /wfij
    listener:
      #max pool size of thread is 10
      max-concurrency: 10
      #核心的listen thread 是3 
      concurrency: 3
      # the container will acknowledge the message automatically, unless the MessageListener throws an exception. Note that acknowledgeMode is complementary to channelTransacted - if the channel is transacted then the broker requires a commit notification in addition to the ack. This is the default mode. See also txSize.
      acknowledge-mode: auto
    
    
    